name: Sample Repro Actions
on:
  workflow_dispatch:
    inputs:
      ip:
        type: string
        description: "IP Address"
      workers:
        type: string
        description: "Number of workers"
      requests:
        type: string
        description: "Number of requests"
jobs:
  sample_test:
    defaults:
      run:
        working-directory: src
    name: Sample Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Timezone 1
        run: |
          echo "The timezone is $TZ"
      - name: Get Timezone 2
        run: |
          echo "The timezone is $(cat /etc/timezone)"
